### ISSUE TITLE
Why is autoConfig (dropwizard-guice) feature removed from this package? 

### ISSUE THREAD

**Issue by neha2016** [HubSpot/dropwizard-guicier#37]
I was using dropwizard-guice where while initializing GuiceBundle I had code fragment like this: `enableAutoConfig(getClass().getPackage().getName(), "some-other-package-name")`
Due to requirements of accessing configuration in Module, I tried to migrate to dropwizard-guicier, but  not sure what's the approach to do the same thing here.

**Comment by kmclarnon** [comment]
We chose to remove the auto-discovery because it was a continual cause of misunderstandings and developer cognitive load.  To that end we decided to require explicit bindings for things that would have been auto-discovered in `dropwizard-guice`.  

If at all possible, I would suggest you not rely on auto-discovery, but if you need to replicate that functionality, you can take a look at how it was implemented [here](https://github.com/HubSpot/dropwizard-guice/blob/master/src/main/java/com/hubspot/dropwizard/guice/AutoConfig.java).  There will be a few differences, and you should be able to do most, if not all, of what you need inside a guice `Module` by installing bindings as eager singletons

**Comment by neha2016** [comment]
Thank you for the response.
