### ISSUE TITLE
Please tell me why is this Guicier than Guicie?

### ISSUE THREAD

**Issue by darrenhaken** [HubSpot/dropwizard-guicier#8]
Never thought I'd ask that on Github...

**Comment by jhaber** [comment]
Hey @darrenhaken thanks for the question! This package was initially extracted from https://github.com/HubSpot/Singularity where it was added by @hgschmie in [this](https://github.com/HubSpot/Singularity/pull/251/files#diff-9a5957ce1bad1c701bcd335538b14b3cR46) PR. The design is a large departure from its predecessor, https://github.com/HubSpot/dropwizard-guice, which is why it's a separate project and wasn't integrated into `dropwizard-guice`.

The most notable change is that the injector is created during the `run` phase rather than the `initialize` phase. This makes it much easier to run Guice in `Stage.PRODUCTION` with eager bindings. Additionally, it does away with the concept of auto-discovered `HealthCheck`, `Managed`, `Task`, etc. It does, however, take any of these classes bound in Guice and register them with dropwizard.

In general, this repo favors eagerness and explicitness, whereas `dropwizard-guice` encouraged implicit magic and laziness.

**Comment by darrenhaken** [comment]
Are you planning on support Guicier in the future?

I'm working on a greenfield Dropwizard project right now and looking to integrate DI into it.

**Comment by jhaber** [comment]
Yup, we'll be keeping it up to date with dropwizard releases

**Comment by darrenhaken** [comment]
That's great! I ran into some issues using the library, if I post a Gist and open an issue will you be able to help?

**Comment by jhaber** [comment]
For sure!

**Comment by darrenhaken** [comment]
Brilliant I'll post it in the next couple of days. Thanks for the speedy reply 👍
